# index.ps1 — PowerShell port of index.sh. Regenerates docs/fluencyloop/README.md, the entry
# point into the docs tree. Deterministic: parses the H1 + front-matter fields new-feature.ps1/
# new-plan.ps1 already write, and computes each feature's status from git — no hand-maintained
# state, so it can never drift from what's actually on disk. Never hand-edit the generated
# file; re-run this after adding a plan/feature (new-feature.ps1 and new-plan.ps1 already do).

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/common.ps1"

$jsonMode = $false
foreach ($a in $args) {
    switch ($a) {
        '--json' { $jsonMode = $true }
        default  { [Console]::Error.WriteLine("Unknown option: $a"); exit 1 }
    }
}

FlRequireFluency

$docs = FlDocsDir
$out = "$docs/README.md"

# Best-effort main/master detection, same fallback order used elsewhere.
$baseRef = FlStateGet 'base_ref'
if (-not $baseRef) {
    foreach ($cand in @('main', 'master')) {
        & git show-ref --verify --quiet "refs/heads/$cand" 2>$null
        if ($LASTEXITCODE -eq 0) { $baseRef = $cand; break }
    }
}
$currentBranch = & git rev-parse --abbrev-ref HEAD 2>$null
if ($LASTEXITCODE -ne 0) { $currentBranch = '' } else { $currentBranch = ($currentBranch | Select-Object -First 1) }

function FlField([string]$name, [string]$file) {
    if (-not (Test-Path -LiteralPath $file)) { return '' }
    $pattern = '^' + [regex]::Escape($name) + ': (.*)$'
    foreach ($l in [System.IO.File]::ReadAllLines($file)) {
        if ($l -match $pattern) { return $matches[1] }
    }
    return ''
}

function FlH1([string]$prefix, [string]$file) {
    if (-not (Test-Path -LiteralPath $file)) { return '' }
    $first = Get-Content -LiteralPath $file -TotalCount 1
    $pattern = '^# ' + [regex]::Escape($prefix) + ': (.*)$'
    if ($first -match $pattern) { return $matches[1] }
    return ''
}

function FlResolveRef([string]$branch) {
    & git show-ref --verify --quiet "refs/heads/$branch" 2>$null
    if ($LASTEXITCODE -eq 0) { return "refs/heads/$branch" }
    & git show-ref --verify --quiet "refs/remotes/origin/$branch" 2>$null
    if ($LASTEXITCODE -eq 0) { return "refs/remotes/origin/$branch" }
    return ''
}

# Heuristic, not certain: a branch that's gone is assumed merged-and-deleted (the common
# `gh pr merge --delete-branch` flow) rather than abandoned, since we can no longer tell the
# difference from git state alone.
function FlFeatureStatus([string]$branch) {
    if ($currentBranch -and $branch -eq $currentBranch) { return 'in progress' }
    $ref = FlResolveRef $branch
    if (-not $ref) { return 'shipped' }
    if ($baseRef) {
        & git merge-base --is-ancestor $ref $baseRef 2>$null
        if ($LASTEXITCODE -eq 0) { return 'shipped' }
    }
    return 'in progress'
}

$planRows = @()
if (Test-Path -LiteralPath "$docs/plans" -PathType Container) {
    foreach ($dir in (Get-ChildItem -LiteralPath "$docs/plans" -Directory -ErrorAction SilentlyContinue | Sort-Object Name)) {
        $planFile = "$($dir.FullName)/plan.md"
        if (-not (Test-Path -LiteralPath $planFile)) { continue }
        $slug = $dir.Name
        $title = FlH1 'Plan' $planFile; if (-not $title) { $title = $slug }
        $started = FlField 'started' $planFile
        $planRows += "| [$title](plans/$slug/plan.md) | $started |"
    }
}

$featureRows = @()
if (Test-Path -LiteralPath "$docs/features" -PathType Container) {
    foreach ($dir in (Get-ChildItem -LiteralPath "$docs/features" -Directory -ErrorAction SilentlyContinue | Sort-Object Name)) {
        $designFile = "$($dir.FullName)/design.md"
        if (-not (Test-Path -LiteralPath $designFile)) { continue }
        $slug = $dir.Name
        $title = FlH1 'Design' $designFile; if (-not $title) { $title = $slug }
        $started = FlField 'started' $designFile
        $branch = FlField 'branch' $designFile; if (-not $branch) { $branch = "feature/$slug" }
        $plan = FlField 'plan' $designFile
        $status = FlFeatureStatus $branch
        $planCell = if ($plan) { $plan } else { '-' }
        $featureRows += "| [$title](features/$slug/design.md) | $planCell | $status | $started |"
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# FluencyLoop docs')
$lines.Add('')
$lines.Add('<!-- Generated by `fluencyloop index` — do not hand-edit; re-run after adding a plan or feature. -->')
$lines.Add('')
if (Test-Path -LiteralPath "$docs/constitution.md") {
    $lines.Add('- [Constitution](constitution.md)')
    $lines.Add('')
}
$lines.Add('## Plans')
$lines.Add('')
if ($planRows.Count -gt 0) {
    $lines.Add('| plan | started |')
    $lines.Add('|------|---------|')
    $lines.AddRange([string[]]$planRows)
} else {
    $lines.Add('_None yet._')
}
$lines.Add('')
$lines.Add('## Features')
$lines.Add('')
if ($featureRows.Count -gt 0) {
    $lines.Add('| feature | plan | status | started |')
    $lines.Add('|---------|------|--------|---------|')
    $lines.AddRange([string[]]$featureRows)
} else {
    $lines.Add('_None yet._')
}

FlWriteText $out (($lines -join "`n") + "`n")

if ($jsonMode) {
    FlOut (FlEmitJson @('out', $out))
} else {
    FlOut "Index: $out"
}
