#!/usr/bin/env bash
# index.sh — regenerate docs/fluencyloop/README.md, the entry point into the docs tree.
# `features/` and `plans/` are otherwise a flat pile of slugs with no status or grouping; this
# is the fix. Deterministic: parses the H1 + front-matter fields each new-feature.sh/new-plan.sh
# already writes, and computes each feature's status from git — no hand-maintained state, so it
# can never drift from what's actually on disk. Never hand-edit the generated file; re-run this
# after adding a plan/feature (new-feature.sh and new-plan.sh already do).
#
# Usage: index.sh [--json]

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

JSON_MODE=false
for arg in "$@"; do
    case "$arg" in
        --json) JSON_MODE=true ;;
        *) echo "Unknown option: $arg" >&2; exit 1 ;;
    esac
done

require_fluency

DOCS="$(docs_dir)"
OUT="$DOCS/README.md"

# Best-effort main/master detection, same fallback order used elsewhere (new-feature.sh,
# assemble-pr-view.sh).
BASE_REF="$(state_get base_ref)"
if [ -z "$BASE_REF" ]; then
    for cand in main master; do
        git show-ref --verify --quiet "refs/heads/$cand" && { BASE_REF="$cand"; break; }
    done
fi
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"

field() { sed -n "s/^$1: //p" "$2" | head -n1; }        # field name, file -> value
h1()    { sed -n "1s/^# $1: //p" "$2" | head -n1; }      # H1 prefix, file -> title

resolve_ref() {
    # A branch's live ref, preferring local over origin; empty if it no longer exists.
    if git show-ref --verify --quiet "refs/heads/$1"; then printf 'refs/heads/%s' "$1"; return; fi
    if git show-ref --verify --quiet "refs/remotes/origin/$1"; then printf 'refs/remotes/origin/%s' "$1"; return; fi
}

feature_status() {
    # Heuristic, not certain: a branch that's gone is assumed merged-and-deleted (the common
    # `gh pr merge --delete-branch` flow) rather than abandoned, since we can no longer tell
    # the difference from git state alone.
    local branch="$1" ref
    if [ -n "$CURRENT_BRANCH" ] && [ "$branch" = "$CURRENT_BRANCH" ]; then
        printf 'in progress'; return
    fi
    ref="$(resolve_ref "$branch")"
    if [ -z "$ref" ]; then
        printf 'shipped'
    elif [ -n "$BASE_REF" ] && git merge-base --is-ancestor "$ref" "$BASE_REF" 2>/dev/null; then
        printf 'shipped'
    else
        printf 'in progress'
    fi
}

PLAN_ROWS=""
if [ -d "$DOCS/plans" ]; then
    for dir in "$DOCS"/plans/*/; do
        [ -d "$dir" ] || continue
        slug="$(basename "$dir")"
        plan_file="$dir/plan.md"
        [ -f "$plan_file" ] || continue
        title="$(h1 Plan "$plan_file")"; [ -n "$title" ] || title="$slug"
        started="$(field started "$plan_file")"
        PLAN_ROWS+="| [$title](plans/$slug/plan.md) | $started |"$'\n'
    done
fi

FEATURE_ROWS=""
if [ -d "$DOCS/features" ]; then
    for dir in "$DOCS"/features/*/; do
        [ -d "$dir" ] || continue
        slug="$(basename "$dir")"
        design_file="$dir/design.md"
        [ -f "$design_file" ] || continue
        title="$(h1 Design "$design_file")"; [ -n "$title" ] || title="$slug"
        started="$(field started "$design_file")"
        branch="$(field branch "$design_file")"; [ -n "$branch" ] || branch="feature/$slug"
        plan="$(field plan "$design_file")"
        status="$(feature_status "$branch")"
        FEATURE_ROWS+="| [$title](features/$slug/design.md) | ${plan:--} | $status | $started |"$'\n'
    done
fi

{
    echo "# FluencyLoop docs"
    echo
    echo "<!-- Generated by \`fluencyloop index\` — do not hand-edit; re-run after adding a plan or feature. -->"
    echo
    if [ -f "$DOCS/constitution.md" ]; then
        echo "- [Constitution](constitution.md)"
        echo
    fi
    echo "## Plans"
    echo
    if [ -n "$PLAN_ROWS" ]; then
        echo "| plan | started |"
        echo "|------|---------|"
        printf '%s' "$PLAN_ROWS"
    else
        echo "_None yet._"
    fi
    echo
    echo "## Features"
    echo
    if [ -n "$FEATURE_ROWS" ]; then
        echo "| feature | plan | status | started |"
        echo "|---------|------|--------|---------|"
        printf '%s' "$FEATURE_ROWS"
    else
        echo "_None yet._"
    fi
} > "$OUT"

if $JSON_MODE; then
    emit_json out "$OUT"
else
    echo "Index: $OUT"
fi
